# 1. Create a 3x3x3 array with random values 

In [6]:
import numpy as np

arr=np.random.random((3,3,3))
print(arr)

[[[0.68689097 0.42456656 0.35578766]
  [0.95695528 0.83417627 0.41573504]
  [0.91809697 0.85734258 0.59661833]]

 [[0.19138695 0.39838348 0.20606254]
  [0.65791704 0.42293651 0.95806207]
  [0.47719458 0.98885605 0.29333643]]

 [[0.0527535  0.79509629 0.21269978]
  [0.15079018 0.66026959 0.86058132]
  [0.2971364  0.84325088 0.77229302]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [9]:
import numpy as np
arr=np.eye(5,5)
arr[0,0]=0
arr[1,1]=1
arr[2,2]=2
arr[3,3]=3
arr[4,4]=4
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 2. 0. 0.]
 [0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 4.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [21]:
a=np.zeros((8,8))
a[::2,::2]=1
a[1::2,1::2]=1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [13]:
import numpy as np
matrix=np.random.random((5,5))
print(matrix)
m=np.mean(matrix)
print("Mean", m)
s=np.std(matrix)
print("standard deviation",s)
nor=m/s
print("normalise", nor)

[[0.061374   0.38696947 0.99574704 0.11391682 0.36784015]
 [0.97711405 0.48921289 0.10890856 0.58257955 0.25827337]
 [0.85113862 0.74938165 0.26796639 0.88258074 0.74712321]
 [0.84227489 0.94928112 0.35480948 0.47231012 0.41549538]
 [0.06636699 0.124079   0.89506962 0.38709223 0.89570758]]
Mean 0.5297045172222797
standard deviation 0.31565086173229373
normalise 1.6781342344996568


# 5.  How to find common values between two arrays?

In [33]:
A=[[1,2,3],[6,7,8]]
B=[[2,3,4],[6,9,0]]
C=np.array(A)
D=np.array(B)
print(np.intersect1d(C,D))

[2 3 6]


# 6.How to get the dates of yesterday, today and tomorrow?

In [41]:
from datetime import date
from datetime import timedelta
today=date.today()
yesterday = today - timedelta(days = 1) 
tom=today+timedelta(days = 1)
print(today)
print(yesterday)
print(tom)

2020-11-09
2020-11-08
2020-11-10


# 7. Consider two random array A and B, check if they are equal

In [46]:
A = np.random.random((2,2))
B = np.random.random((2,2))

C=np.array([[1,2],[3,4]])
D=np.array([[1,2],[3,4]])

equal = np.allclose(A,B)
print(equal)

equal = np.array_equal(A,B)
print(equal)
equal1 = np.allclose(C,D)
print(equal1)

False
False
True


# 8.Create random vector of size 10 and replace the maximum value by 0 

# 9. How to print all the values of an array?

In [32]:
V=np.random.random((4,4))
print(V)

[[0.48174845 0.96917829 0.52303217 0.36685996]
 [0.65972073 0.14718085 0.08347185 0.0660043 ]
 [0.13192052 0.68862619 0.75541233 0.18040236]
 [0.00341661 0.98005795 0.31703097 0.77554726]]


# 10.Subtract the mean of each row of a matrix

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

# 12.How to get the diagonal of a dot product?

# 13.How to find the most frequent value in an array?

In [47]:
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z).argmax())

[4 3 8 2 7 0 3 4 1 3 8 3 4 2 7 4 4 0 7 3 8 1 5 2 9 9 5 3 1 2 0 7 5 1 0 6 8
 2 2 7 8 8 2 7 6 8 5 3 7 4]
2


# 14.How to get the n largest values of an array

In [49]:
Z = np.arange(10)
np.random.shuffle(Z)
n = 3


print (Z[np.argsort(Z)[-n:]])


[7 8 9]


# 15.How to create a record array from a regular array?